<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class WargasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('wargas')->delete();
        
        \DB::table('wargas')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nama' => 'Rifqi Munawar Ridwan',
                'telp' => '085151145097',
                'alamat' => 'D7 No. 11',
                'nik' => '3203210512010003',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Cianjur',
                'tgl_lahir' => '2001-11-05',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '12',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-01-17 11:30:04',
                'updated_at' => '2025-02-09 01:20:09',
            ),
            1 => 
            array (
                'id' => 2,
                'nama' => 'HENDRA SUPRIADI',
                'telp' => '085151145097',
                'alamat' => 'Blok A',
                'nik' => '3203210512010003',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Bandung',
                'tgl_lahir' => '2007-02-06',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '12',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-01-18 20:02:11',
                'updated_at' => '2025-01-18 22:25:27',
            ),
            2 => 
            array (
                'id' => 3,
                'nama' => 'Udin Petot',
                'telp' => '085151145097',
                'alamat' => 'bandung',
                'nik' => '1278010404040004',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Bandung',
                'tgl_lahir' => '2007-02-06',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '12',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-01-21 00:34:20',
                'updated_at' => '2025-01-21 00:34:20',
            ),
            3 => 
            array (
                'id' => 4,
                'nama' => 'Ronaldo',
                'telp' => '085151145097',
                'alamat' => 'portugal',
                'nik' => '1278010404040004',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Bandung',
                'tgl_lahir' => '2007-02-06',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '12',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-01-21 00:38:58',
                'updated_at' => '2025-01-21 00:38:58',
            ),
            4 => 
            array (
                'id' => 5,
                'nama' => 'Leonel Messi',
                'telp' => '085151145097',
                'alamat' => 'argentina',
                'nik' => '1278010404040004',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Bandung',
                'tgl_lahir' => '2007-02-06',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '12',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-01-21 00:39:18',
                'updated_at' => '2025-01-21 00:39:18',
            ),
            5 => 
            array (
                'id' => 6,
                'nama' => 'Antony El-Gasing',
                'telp' => '085151145097',
                'alamat' => 'Al hilal',
                'nik' => '3203210000000',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Bandung',
                'tgl_lahir' => '2007-02-06',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '12',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-02-09 00:59:35',
                'updated_at' => '2025-02-09 00:59:35',
            ),
            6 => 
            array (
                'id' => 7,
                'nama' => 'SAMANI BIN TUKIMIN',
                'telp' => '085151145097',
                'alamat' => 'BLOK PON',
                'nik' => '085624011773',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Cirebon',
                'tgl_lahir' => '2025-02-02',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '7',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-02-09 21:09:55',
                'updated_at' => '2025-03-02 17:44:36',
            ),
            7 => 
            array (
                'id' => 8,
                'nama' => 'Dilan',
                'telp' => '085151145097',
                'alamat' => 'Cirebon',
                'nik' => '1278010404040004',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Bandung',
                'tgl_lahir' => '2007-02-06',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '3',
                'pekerjaan' => '12',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-02-24 21:39:39',
                'updated_at' => '2025-03-08 17:18:18',
            ),
            8 => 
            array (
                'id' => 9,
                'nama' => 'Budi Santoso',
                'telp' => '081345678912',
                'alamat' => 'Bandung',
                'nik' => '3275010303030003',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Bandung',
                'tgl_lahir' => '1987-12-10',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '4',
                'pekerjaan' => '10',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-02-24 21:39:39',
                'updated_at' => '2025-03-08 17:18:33',
            ),
            9 => 
            array (
                'id' => 10,
                'nama' => 'Dewi Lestari',
                'telp' => '089876543210',
                'alamat' => 'Medan',
                'nik' => '1278010404040004',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Medan',
                'tgl_lahir' => '1998-04-05',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '15',
                'status_perkawinan' => '1',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-02-24 21:39:39',
                'updated_at' => '2025-03-08 17:19:11',
            ),
            10 => 
            array (
                'id' => 11,
                'nama' => 'Eko Prasetyo',
                'telp' => '081290876543',
                'alamat' => 'Yogyakarta',
                'nik' => '3471010505050005',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Yogyakarta',
                'tgl_lahir' => '1992-09-30',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '2',
                'pekerjaan' => '10',
                'status_perkawinan' => '3',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-02-24 21:39:39',
                'updated_at' => '2025-03-08 17:19:32',
            ),
            11 => 
            array (
                'id' => 12,
                'nama' => 'Indah Permata',
                'telp' => '082134567890',
                'alamat' => 'Semarang',
                'nik' => '3374010606060006',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Semarang',
                'tgl_lahir' => '2000-03-18',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '4',
                'pekerjaan' => '2',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-02-24 21:39:39',
                'updated_at' => '2025-02-24 21:45:39',
            ),
            12 => 
            array (
                'id' => 13,
                'nama' => 'Rudi Hartono',
                'telp' => '085678909876',
                'alamat' => 'Palembang',
                'nik' => '1671010707070007',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Palembang',
                'tgl_lahir' => '1985-06-12',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '4',
                'pekerjaan' => '2',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-02-24 21:39:39',
                'updated_at' => '2025-02-24 21:45:39',
            ),
            13 => 
            array (
                'id' => 14,
                'nama' => 'Sari Wulandari',
                'telp' => '089012345678',
                'alamat' => 'Makassar',
                'nik' => '7371010808080008',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Makassar',
                'tgl_lahir' => '1997-01-23',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '4',
                'pekerjaan' => '2',
                'status_perkawinan' => '2',
                'status_keluarga' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-02-24 21:39:39',
                'updated_at' => '2025-02-24 21:45:39',
            ),
            14 => 
            array (
                'id' => 15,
                'nama' => 'Maya Indriyani',
                'telp' => '+6287346168005',
                'alamat' => '136 Dovie Drive
Port Jedediahberg, AK 34507-3064',
                'nik' => '7122875240870232',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Hillston',
                'tgl_lahir' => '1996-01-20',
                'agama' => '2',
                'pendapatan' => 90000,
                'pendidikan' => '6',
                'pekerjaan' => '5',
                'status_perkawinan' => '3',
                'status_keluarga' => '819026026',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-05-05 14:28:26',
            ),
            15 => 
            array (
                'id' => 16,
                'nama' => 'Alexandra Putra',
                'telp' => '+6281730462230',
                'alamat' => '83800 Raymond Pine Apt. 923
Antoinetteland, NJ 17938-9977',
                'nik' => '2730859627786851',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Abigayleshire',
                'tgl_lahir' => '1991-08-24',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '11',
                'status_perkawinan' => '2',
                'status_keluarga' => '785479402',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            16 => 
            array (
                'id' => 17,
                'nama' => 'Vina Aprilia',
                'telp' => '+6280771953401',
                'alamat' => '98862 D\'Amore View
East Brownburgh, VT 93573',
                'nik' => '5445622567535125',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Jonfort',
                'tgl_lahir' => '2002-04-05',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '17',
                'status_perkawinan' => '3',
                'status_keluarga' => '1831755700',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            17 => 
            array (
                'id' => 18,
                'nama' => 'Ridho Alamsyah',
                'telp' => '+6289546919461',
                'alamat' => '24042 Madelyn Common
West Lucileside, UT 57818',
                'nik' => '3305002801976637',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Handtown',
                'tgl_lahir' => '1995-01-20',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '11',
                'status_perkawinan' => '4',
                'status_keluarga' => '392281740',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            18 => 
            array (
                'id' => 19,
                'nama' => 'Mega Putri',
                'telp' => '+6281282357935',
                'alamat' => '684 Weimann Plains Suite 054
Nonaport, ND 44437',
                'nik' => '8812490251383563',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Kreigerhaven',
                'tgl_lahir' => '1997-06-07',
                'agama' => '4',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '2',
                'status_perkawinan' => '1',
                'status_keluarga' => '2087613875',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            19 => 
            array (
                'id' => 20,
                'nama' => 'Rendi Prasetyo',
                'telp' => '+6287695385782',
                'alamat' => '5409 King Squares
East Charlie, TX 08483',
                'nik' => '9939370363220659',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Metaberg',
                'tgl_lahir' => '1997-11-17',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '1',
                'pekerjaan' => '3',
                'status_perkawinan' => '4',
                'status_keluarga' => '607851197',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            20 => 
            array (
                'id' => 21,
                'nama' => 'Nabila Aprilia',
                'telp' => '+6284890195411',
                'alamat' => '807 Kira Tunnel Suite 163
Lake Jewelburgh, NV 05494',
                'nik' => '6171861265631792',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Feliciaberg',
                'tgl_lahir' => '1992-11-16',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '6',
                'pekerjaan' => '12',
                'status_perkawinan' => '2',
                'status_keluarga' => '1968945978',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            21 => 
            array (
                'id' => 22,
                'nama' => 'Novi Andriani',
                'telp' => '+6289482403279',
                'alamat' => '28339 Jewel Via Apt. 156
Matteoville, AK 18032-4460',
                'nik' => '1561918371107712',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Clementinehaven',
                'tgl_lahir' => '1999-04-12',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '1',
                'status_perkawinan' => '2',
                'status_keluarga' => '538833120',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            22 => 
            array (
                'id' => 23,
                'nama' => 'Maya Indriyani',
                'telp' => '+6288609383666',
                'alamat' => '3147 Nils Curve Apt. 971
Kihnfort, OH 72125',
                'nik' => '7396773259308453',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Hoppefurt',
                'tgl_lahir' => '1997-12-08',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '6',
                'pekerjaan' => '19',
                'status_perkawinan' => '3',
                'status_keluarga' => '729607314',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            23 => 
            array (
                'id' => 24,
                'nama' => 'Joko Prabowo',
                'telp' => '+6285241930210',
                'alamat' => '60726 Deja Hill Suite 673
West Hettie, VA 34461',
                'nik' => '7794403107066762',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Port Jackystad',
                'tgl_lahir' => '2001-12-31',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '8',
                'status_perkawinan' => '1',
                'status_keluarga' => '118443019',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            24 => 
            array (
                'id' => 25,
                'nama' => 'Galih Saputra',
                'telp' => '+6289992528956',
                'alamat' => '57502 Stamm Corner Apt. 066
South Clarissa, AZ 70922',
                'nik' => '7693102711748997',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Emersonmouth',
                'tgl_lahir' => '1995-01-10',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '3',
                'pekerjaan' => '20',
                'status_perkawinan' => '4',
                'status_keluarga' => '1996750721',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            25 => 
            array (
                'id' => 26,
                'nama' => 'Ayu Lestari',
                'telp' => '+6289864079231',
                'alamat' => '73597 Francisca Gardens Suite 914
Concepcionberg, DC 17980-4871',
                'nik' => '5176665966190955',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'North Idell',
                'tgl_lahir' => '1996-06-16',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '14',
                'status_perkawinan' => '4',
                'status_keluarga' => '1566381873',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            26 => 
            array (
                'id' => 27,
                'nama' => 'Diana Permatasari',
                'telp' => '+6282860160104',
                'alamat' => '1232 Guy Ports
Wisokyhaven, MI 65087',
                'nik' => '7925947382651848',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'New Marilou',
                'tgl_lahir' => '2003-03-13',
                'agama' => '4',
                'pendapatan' => NULL,
                'pendidikan' => '1',
                'pekerjaan' => '18',
                'status_perkawinan' => '3',
                'status_keluarga' => '1187237354',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            27 => 
            array (
                'id' => 28,
                'nama' => 'Fahmi Aditya',
                'telp' => '+6287536923001',
                'alamat' => '78809 Jakayla Springs
Savanahport, FL 83253',
                'nik' => '0432225556811590',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Crooksport',
                'tgl_lahir' => '1998-07-15',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '3',
                'pekerjaan' => '10',
                'status_perkawinan' => '3',
                'status_keluarga' => '844011085',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            28 => 
            array (
                'id' => 29,
                'nama' => 'Wulan Sari',
                'telp' => '+6286368983224',
                'alamat' => '14640 Stephany Square
Johnathonmouth, WA 52156',
                'nik' => '9152906163998794',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Lake Milesmouth',
                'tgl_lahir' => '1992-06-30',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '1',
                'pekerjaan' => '4',
                'status_perkawinan' => '2',
                'status_keluarga' => '797454501',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            29 => 
            array (
                'id' => 30,
                'nama' => 'Fikri Irawan',
                'telp' => '+6282844723091',
                'alamat' => '9974 Klocko Squares Suite 268
West Ocie, HI 37105',
                'nik' => '6305569549204242',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Bergstromton',
                'tgl_lahir' => '2003-03-19',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '9',
                'status_perkawinan' => '3',
                'status_keluarga' => '1102074069',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            30 => 
            array (
                'id' => 31,
                'nama' => 'Fajar Nugroho',
                'telp' => '+6289628114691',
                'alamat' => '706 Hoeger Crossroad Suite 238
Stammburgh, MS 44637-2817',
                'nik' => '6906598566985529',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Delphineside',
                'tgl_lahir' => '1995-04-29',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '3',
                'pekerjaan' => '2',
                'status_perkawinan' => '4',
                'status_keluarga' => '1757945306',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            31 => 
            array (
                'id' => 32,
                'nama' => 'Nia Ramadhani',
                'telp' => '+6282087849534',
                'alamat' => '44578 Clyde Village
West Elwynville, MO 54909',
                'nik' => '5992701334160805',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'North Woodrowbury',
                'tgl_lahir' => '2005-04-17',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '4',
                'pekerjaan' => '12',
                'status_perkawinan' => '4',
                'status_keluarga' => '1742436167',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            32 => 
            array (
                'id' => 33,
                'nama' => 'Arif Rahman',
                'telp' => '+6286188918451',
                'alamat' => '7800 Leola Expressway Suite 383
Gerdashire, MD 49335-8640',
                'nik' => '7110536265940081',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'South Daishaside',
                'tgl_lahir' => '1991-09-22',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '1',
                'status_perkawinan' => '3',
                'status_keluarga' => '258177767',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            33 => 
            array (
                'id' => 34,
                'nama' => 'Slamet Riyadi',
                'telp' => '+6287959853484',
                'alamat' => '354 Gulgowski Junctions Suite 686
Wunschburgh, NC 18753-5274',
                'nik' => '6801062511573083',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Wizafurt',
                'tgl_lahir' => '1996-03-27',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '2',
                'pekerjaan' => '3',
                'status_perkawinan' => '1',
                'status_keluarga' => '104515891',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            34 => 
            array (
                'id' => 35,
                'nama' => 'Andi Wijaya',
                'telp' => '+6285732852933',
                'alamat' => '855 Jaclyn Well
Khalilview, SD 39553',
                'nik' => '0737180237207192',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Mafaldafort',
                'tgl_lahir' => '1999-11-05',
                'agama' => '4',
                'pendapatan' => NULL,
                'pendidikan' => '3',
                'pekerjaan' => '1',
                'status_perkawinan' => '3',
                'status_keluarga' => '1447320409',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            35 => 
            array (
                'id' => 36,
                'nama' => 'Wahyu Nugroho',
                'telp' => '+6287668335960',
                'alamat' => '83516 Dibbert Spring Apt. 374
Port Patience, NV 30764-9050',
                'nik' => '2596029144378623',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Kulasport',
                'tgl_lahir' => '1991-05-11',
                'agama' => '4',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '6',
                'status_perkawinan' => '3',
                'status_keluarga' => '1017401284',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            36 => 
            array (
                'id' => 37,
                'nama' => 'Slamet Riyadi',
                'telp' => '+6288444268113',
                'alamat' => '326 Farrell Green Apt. 481
Santinoside, MN 13273',
                'nik' => '5450446387706630',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Steuberfurt',
                'tgl_lahir' => '2004-10-11',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '13',
                'status_perkawinan' => '4',
                'status_keluarga' => '1958840189',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            37 => 
            array (
                'id' => 38,
                'nama' => 'Nabila Aprilia',
                'telp' => '+6281274434457',
                'alamat' => '770 Shanie Parkway Suite 148
North Khalid, ME 16171',
                'nik' => '7667511731495989',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'South Candice',
                'tgl_lahir' => '2005-08-31',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '11',
                'status_perkawinan' => '3',
                'status_keluarga' => '1557727948',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            38 => 
            array (
                'id' => 39,
                'nama' => 'Yuni Kartika',
                'telp' => '+6288227305117',
                'alamat' => '82974 Stacy Ridges Suite 235
Anyatown, OH 13248-7264',
                'nik' => '8102471074911852',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Erwinview',
                'tgl_lahir' => '1993-06-12',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '3',
                'pekerjaan' => '8',
                'status_perkawinan' => '4',
                'status_keluarga' => '1866196584',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            39 => 
            array (
                'id' => 40,
                'nama' => 'Rina Marlina',
                'telp' => '+6288317178526',
                'alamat' => '2237 Maci Key Suite 421
West Evalynmouth, TN 51404',
                'nik' => '6255641386985048',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'South Mandy',
                'tgl_lahir' => '1996-05-26',
                'agama' => '4',
                'pendapatan' => NULL,
                'pendidikan' => '6',
                'pekerjaan' => '14',
                'status_perkawinan' => '1',
                'status_keluarga' => '210884593',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            40 => 
            array (
                'id' => 41,
                'nama' => 'Ari Wibowo',
                'telp' => '+6281917339338',
                'alamat' => '225 Lockman Ways Apt. 421
West Maraton, MO 37829',
                'nik' => '4944804813595146',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'O\'Reillyburgh',
                'tgl_lahir' => '1998-01-13',
                'agama' => '4',
                'pendapatan' => NULL,
                'pendidikan' => '2',
                'pekerjaan' => '5',
                'status_perkawinan' => '2',
                'status_keluarga' => '1758871616',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            41 => 
            array (
                'id' => 42,
                'nama' => 'Diana Permatasari',
                'telp' => '+6285665007574',
                'alamat' => '9062 Brekke Cliff Apt. 791
Hudsonland, HI 97163-7694',
                'nik' => '3897893729869078',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Lake Alishamouth',
                'tgl_lahir' => '2001-02-07',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '4',
                'status_perkawinan' => '4',
                'status_keluarga' => '431512842',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            42 => 
            array (
                'id' => 43,
                'nama' => 'Yoga Permana',
                'telp' => '+6287527496507',
                'alamat' => '69873 Weber Forest
Casperborough, AK 12737',
                'nik' => '3253975293187905',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Lednerchester',
                'tgl_lahir' => '1993-10-12',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '5',
                'pekerjaan' => '5',
                'status_perkawinan' => '1',
                'status_keluarga' => '1190961469',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            43 => 
            array (
                'id' => 44,
                'nama' => 'Fahmi Aditya',
                'telp' => '+6284274434219',
                'alamat' => '3934 Mitchel Track
Micaelaville, WA 93500',
                'nik' => '0669187709410091',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Gottliebborough',
                'tgl_lahir' => '1992-03-13',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '3',
                'pekerjaan' => '17',
                'status_perkawinan' => '1',
                'status_keluarga' => '1007119827',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            44 => 
            array (
                'id' => 45,
                'nama' => 'Joko Prabowo',
                'telp' => '+6285292352216',
                'alamat' => '780 Joelle Track Apt. 106
North Sylvan, AL 18645-4882',
                'nik' => '7058564397475896',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Stokesside',
                'tgl_lahir' => '1994-03-13',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '4',
                'pekerjaan' => '6',
                'status_perkawinan' => '1',
                'status_keluarga' => '353433076',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            45 => 
            array (
                'id' => 46,
                'nama' => 'Tari Wulandari',
                'telp' => '+6287337533672',
                'alamat' => '8542 Raheem Dale Suite 952
New Margaretta, PA 29054',
                'nik' => '2641736620049263',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'North Nathanielshire',
                'tgl_lahir' => '1993-11-07',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '13',
                'status_perkawinan' => '3',
                'status_keluarga' => '1740218291',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            46 => 
            array (
                'id' => 47,
                'nama' => 'Rian Firmansyah',
                'telp' => '+6283353227392',
                'alamat' => '49372 Torphy Alley Suite 776
Binsville, MD 60969',
                'nik' => '4671058914313854',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Kittybury',
                'tgl_lahir' => '1997-12-24',
                'agama' => '4',
                'pendapatan' => NULL,
                'pendidikan' => '1',
                'pekerjaan' => '15',
                'status_perkawinan' => '2',
                'status_keluarga' => '941284692',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            47 => 
            array (
                'id' => 48,
                'nama' => 'Rina Marlina',
                'telp' => '+6281978119680',
                'alamat' => '84733 Murray Drive
Collinshaven, RI 60799-2944',
                'nik' => '4141159986071178',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Sylvesterstad',
                'tgl_lahir' => '1998-12-25',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '2',
                'pekerjaan' => '3',
                'status_perkawinan' => '2',
                'status_keluarga' => '364386161',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            48 => 
            array (
                'id' => 49,
                'nama' => 'Tari Wulandari',
                'telp' => '+6287585245995',
                'alamat' => '386 Lemke Mews
Elishaside, ND 92280',
                'nik' => '0219219362009755',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Lake Susantown',
                'tgl_lahir' => '2005-12-10',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '10',
                'status_perkawinan' => '1',
                'status_keluarga' => '1497171131',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            49 => 
            array (
                'id' => 50,
                'nama' => 'Nurul Hidayati',
                'telp' => '+6288456687347',
                'alamat' => '577 Myrtle Road
West Devin, MS 79094-4717',
                'nik' => '6886616671434795',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Derekfort',
                'tgl_lahir' => '2005-04-20',
                'agama' => '4',
                'pendapatan' => NULL,
                'pendidikan' => '6',
                'pekerjaan' => '3',
                'status_perkawinan' => '2',
                'status_keluarga' => '230066229',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            50 => 
            array (
                'id' => 51,
                'nama' => 'Nabila Aprilia',
                'telp' => '+6282859151142',
                'alamat' => '5887 Estevan Dale
Funkstad, DE 82154-3049',
                'nik' => '8068943935117587',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'West Newtonfurt',
                'tgl_lahir' => '2005-04-08',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '18',
                'status_perkawinan' => '1',
                'status_keluarga' => '1351758543',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            51 => 
            array (
                'id' => 52,
                'nama' => 'Ricky Maulana',
                'telp' => '+6287052225174',
                'alamat' => '712 Clara Shoals
North Jenniefort, CT 11510-5208',
                'nik' => '9286932311466927',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Mauriceberg',
                'tgl_lahir' => '1994-07-15',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '14',
                'status_perkawinan' => '2',
                'status_keluarga' => '1131241118',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            52 => 
            array (
                'id' => 53,
                'nama' => 'Hendra Gunawan',
                'telp' => '+6281956707428',
                'alamat' => '3855 Candido Terrace
Weimannfurt, IL 88227-6525',
                'nik' => '0856590345967958',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Leviside',
                'tgl_lahir' => '1993-01-27',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '7',
                'pekerjaan' => '14',
                'status_perkawinan' => '4',
                'status_keluarga' => '965408834',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            53 => 
            array (
                'id' => 54,
                'nama' => 'Dedi Kurniawan',
                'telp' => '+6288531163274',
                'alamat' => '19541 O\'Keefe Islands
Amostown, KY 06622',
                'nik' => '3675970664707760',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'West Janiceberg',
                'tgl_lahir' => '1999-03-14',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '1',
                'pekerjaan' => '16',
                'status_perkawinan' => '4',
                'status_keluarga' => '349315856',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            54 => 
            array (
                'id' => 55,
                'nama' => 'Dewi Sartika',
                'telp' => '+6281416848634',
                'alamat' => '315 Hodkiewicz Dam
Lake Montybury, KY 42255',
                'nik' => '1411888430119363',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Camrenfort',
                'tgl_lahir' => '1992-10-31',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '6',
                'pekerjaan' => '20',
                'status_perkawinan' => '4',
                'status_keluarga' => '1874453190',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            55 => 
            array (
                'id' => 56,
                'nama' => 'Dimas Kurniawan',
                'telp' => '+6288572444032',
                'alamat' => '2691 Tina Stream Apt. 111
Spencerfurt, KS 13558-5504',
                'nik' => '7056892523209932',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'South Marty',
                'tgl_lahir' => '1998-12-12',
                'agama' => '4',
                'pendapatan' => NULL,
                'pendidikan' => '1',
                'pekerjaan' => '12',
                'status_perkawinan' => '3',
                'status_keluarga' => '1853609916',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            56 => 
            array (
                'id' => 57,
                'nama' => 'Sari Indah',
                'telp' => '+6283139904527',
                'alamat' => '43123 Rick Path Suite 961
Austinhaven, WY 38554-5274',
                'nik' => '1080929201956349',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Sibylhaven',
                'tgl_lahir' => '1999-06-09',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '3',
                'pekerjaan' => '1',
                'status_perkawinan' => '1',
                'status_keluarga' => '209576030',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            57 => 
            array (
                'id' => 58,
                'nama' => 'Putri Kartika',
                'telp' => '+6285348680393',
                'alamat' => '6928 Wisoky Motorway
Dickinsonhaven, OK 20835-4058',
                'nik' => '1780139827833195',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'East Natasha',
                'tgl_lahir' => '1999-12-15',
                'agama' => '1',
                'pendapatan' => NULL,
                'pendidikan' => '2',
                'pekerjaan' => '13',
                'status_perkawinan' => '1',
                'status_keluarga' => '1416601530',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            58 => 
            array (
                'id' => 59,
                'nama' => 'Ferry Anugrah',
                'telp' => '+6285110846508',
                'alamat' => '5563 Okuneva Fork
South Bernitamouth, NE 42956-3830',
                'nik' => '8222137750402285',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'New German',
                'tgl_lahir' => '1997-02-24',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '3',
                'pekerjaan' => '1',
                'status_perkawinan' => '2',
                'status_keluarga' => '2096736164',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            59 => 
            array (
                'id' => 60,
                'nama' => 'Nabila Aprilia',
                'telp' => '+6283077771088',
                'alamat' => '38664 Rolfson Square Suite 495
South Vickyland, OH 27605',
                'nik' => '6138901958526745',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Feeneyfurt',
                'tgl_lahir' => '1993-12-24',
                'agama' => '4',
                'pendapatan' => NULL,
                'pendidikan' => '6',
                'pekerjaan' => '19',
                'status_perkawinan' => '2',
                'status_keluarga' => '2018685998',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            60 => 
            array (
                'id' => 61,
                'nama' => 'Hendra Gunawan',
                'telp' => '+6284541617549',
                'alamat' => '9435 Lesch Fork Suite 768
Lake Bulah, IA 81766-9816',
                'nik' => '0640431466057796',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'North Arthurborough',
                'tgl_lahir' => '1998-11-27',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '4',
                'pekerjaan' => '13',
                'status_perkawinan' => '3',
                'status_keluarga' => '1166000257',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            61 => 
            array (
                'id' => 62,
                'nama' => 'Anisa Rahma',
                'telp' => '+6284751134138',
                'alamat' => '655 Jany Run Suite 793
West Alta, NH 21966',
                'nik' => '4402514654359764',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'Zanderview',
                'tgl_lahir' => '2002-06-21',
                'agama' => '2',
                'pendapatan' => NULL,
                'pendidikan' => '4',
                'pekerjaan' => '10',
                'status_perkawinan' => '3',
                'status_keluarga' => '1200476624',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            62 => 
            array (
                'id' => 63,
                'nama' => 'Yuni Kartika',
                'telp' => '+6287433857659',
                'alamat' => '35665 Cormier Station Apt. 798
Lake Leonardo, NH 84372-0791',
                'nik' => '4483345758703621',
                'jk' => 'Perempuan',
                'kota_kelahiran' => 'Franeckifort',
                'tgl_lahir' => '2004-07-27',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '1',
                'pekerjaan' => '9',
                'status_perkawinan' => '1',
                'status_keluarga' => '800873445',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
            63 => 
            array (
                'id' => 64,
                'nama' => 'Ratna Dewi',
                'telp' => '+6287922801338',
                'alamat' => '667 Jerde Tunnel Suite 521
Alfredastad, NM 80525-1210',
                'nik' => '3556216020453384',
                'jk' => 'Laki-laki',
                'kota_kelahiran' => 'West Alisabury',
                'tgl_lahir' => '1993-07-14',
                'agama' => '3',
                'pendapatan' => NULL,
                'pendidikan' => '4',
                'pekerjaan' => '2',
                'status_perkawinan' => '3',
                'status_keluarga' => '613463432',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-04-11 14:30:13',
                'updated_at' => '2025-04-11 14:30:13',
            ),
        ));
        
        
    }
}