<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Dashboard',
                'url' => '/',
                'route-name' => NULL,
                'icon' => 'fa fa-sitemap',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-12-13 19:29:15',
                'updated_at' => '2024-12-19 17:07:27',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Settings',
                'url' => '/settings',
                'route-name' => NULL,
                'icon' => 'fa fa-cogs',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-12-13 19:29:33',
                'updated_at' => '2024-12-13 19:29:33',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Modul / Menu',
                'url' => '/settings/menu',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-12-19 16:29:24',
                'updated_at' => '2025-05-20 21:34:42',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Role Akses',
                'url' => '/settings/role',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-12-19 16:29:51',
                'updated_at' => '2025-06-25 19:30:33',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'General Settings',
                'url' => '/settings/general',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-12-19 16:30:26',
                'updated_at' => '2024-12-19 16:34:41',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'User Management',
                'url' => '/users',
                'route-name' => NULL,
                'icon' => 'fa fa-users',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-12-19 16:31:27',
                'updated_at' => '2025-06-09 11:39:34',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Master Data',
                'url' => '/master',
                'route-name' => NULL,
                'icon' => 'fa fa-database',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-05-20 21:34:29',
                'created_at' => '2024-12-21 15:45:55',
                'updated_at' => '2025-05-20 21:34:29',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Laporan',
                'url' => '/laporan',
                'route-name' => NULL,
                'icon' => 'fa fa-book',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-05-05 14:24:11',
                'created_at' => '2024-12-21 15:47:19',
                'updated_at' => '2025-05-05 14:24:11',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Register Tamu',
                'url' => '/tamu',
                'route-name' => NULL,
                'icon' => 'fa fa-user',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-01-18 19:50:22',
                'created_at' => '2024-12-21 15:48:01',
                'updated_at' => '2025-01-18 19:50:22',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Register Karyawan',
                'url' => '/karyawan',
                'route-name' => NULL,
                'icon' => 'fa fa-address-card',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-01-18 19:50:08',
                'created_at' => '2024-12-21 17:09:35',
                'updated_at' => '2025-01-18 19:50:08',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Jenis kendaraan',
                'url' => '/master/jenis_kendaraan',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 7,
                'deleted_at' => '2025-01-18 19:51:01',
                'created_at' => '2024-12-21 17:24:36',
                'updated_at' => '2025-01-18 19:51:01',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Laporan Keuangan',
                'url' => '/lap/keuangan',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 8,
                'deleted_at' => '2025-02-25 13:29:58',
                'created_at' => '2024-12-21 17:29:39',
                'updated_at' => '2025-02-25 13:29:58',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Posisi / Jabatan',
                'url' => '/master/posisi',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 7,
                'deleted_at' => '2025-01-18 19:50:54',
                'created_at' => '2024-12-22 02:23:36',
                'updated_at' => '2025-01-18 19:50:54',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Karyawan',
                'url' => '/master/karyawan',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 7,
                'deleted_at' => '2025-01-18 19:50:38',
                'created_at' => '2024-12-22 03:15:36',
                'updated_at' => '2025-01-18 19:50:38',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Data Warga',
                'url' => '/master/warga',
                'route-name' => NULL,
                'icon' => 'fa fa-users',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 7,
                'deleted_at' => '2025-04-23 09:01:40',
                'created_at' => '2025-01-17 11:11:15',
                'updated_at' => '2025-04-23 09:01:40',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Data Tagihan delete',
                'url' => '/tgh',
                'route-name' => NULL,
                'icon' => 'fa fa-credit-card',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-01-18 19:50:38',
                'created_at' => '2025-01-18 19:47:22',
                'updated_at' => '2025-01-18 22:43:11',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Data Blok',
                'url' => '/master/blok',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => 7,
                'deleted_at' => '2025-04-23 09:04:16',
                'created_at' => '2025-01-18 19:48:07',
                'updated_at' => '2025-04-23 09:04:16',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Ronda',
                'url' => '/ronda/',
                'route-name' => NULL,
                'icon' => 'fa fa-shield',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-04-23 09:04:44',
                'created_at' => '2025-01-18 19:49:04',
                'updated_at' => '2025-04-23 09:04:44',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Tagihan Rutin',
                'url' => '/tagihan/umum',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 22,
                'deleted_at' => '2025-04-23 09:07:00',
                'created_at' => '2025-01-18 22:32:42',
                'updated_at' => '2025-04-23 09:07:00',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Kas Pam Swadaya',
                'url' => '/tagihan/pam',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 22,
                'deleted_at' => '2025-04-23 09:07:06',
                'created_at' => '2025-01-18 22:33:33',
                'updated_at' => '2025-04-23 09:07:06',
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Pembayaran',
                'url' => '/pembayaran',
                'route-name' => NULL,
                'icon' => 'fa fa-shopping-basket',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-04-23 09:07:13',
                'created_at' => '2025-01-18 22:36:20',
                'updated_at' => '2025-04-23 09:07:13',
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Tagihan',
                'url' => '/tagihan',
                'route-name' => NULL,
                'icon' => 'fa fa-credit-card',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-04-23 09:06:40',
                'created_at' => '2025-01-18 22:36:20',
                'updated_at' => '2025-04-23 09:06:40',
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'Laporan Absen',
                'url' => '/lap/absen',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 8,
                'deleted_at' => '2025-04-23 09:06:26',
                'created_at' => '2025-01-18 22:52:49',
                'updated_at' => '2025-04-23 09:06:26',
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'Laporan Warga',
                'url' => '/lap/warga',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 8,
                'deleted_at' => '2025-04-23 09:04:59',
                'created_at' => '2025-01-18 22:53:21',
                'updated_at' => '2025-04-23 09:04:59',
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Pengumuman',
                'url' => '/pengumuman',
                'route-name' => NULL,
                'icon' => 'fa fa-microphone',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-04-23 09:06:15',
                'created_at' => '2025-01-18 22:56:56',
                'updated_at' => '2025-04-23 09:06:15',
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'Periode',
                'url' => '/master/periode',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 7,
                'deleted_at' => '2025-04-23 09:01:26',
                'created_at' => '2025-01-18 23:34:42',
                'updated_at' => '2025-04-23 09:01:26',
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'Jadwal Ronda',
                'url' => '/ronda/jadwal',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 18,
                'deleted_at' => '2025-04-23 09:04:32',
                'created_at' => '2025-01-21 01:12:01',
                'updated_at' => '2025-04-23 09:04:32',
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Jadwalkan Ronda',
                'url' => '/ronda/jadwalkan',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 18,
                'deleted_at' => '2025-04-23 09:04:39',
                'created_at' => '2025-01-21 01:12:28',
                'updated_at' => '2025-04-23 09:04:39',
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Pengajuan Surat',
                'url' => '/surat',
                'route-name' => NULL,
                'icon' => 'fa fa-envelope',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-04-23 09:05:40',
                'created_at' => '2025-01-21 02:24:29',
                'updated_at' => '2025-04-23 09:05:40',
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'Tagihan Ronda',
                'url' => '/tagihan/ronda',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 22,
                'deleted_at' => '2025-04-23 09:03:48',
                'created_at' => '2025-01-21 02:26:00',
                'updated_at' => '2025-04-23 09:03:48',
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'Parameter',
                'url' => '/master/parameter',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 7,
                'deleted_at' => '2025-05-05 14:24:06',
                'created_at' => '2025-02-03 11:35:48',
                'updated_at' => '2025-05-05 14:24:06',
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'Laporan Pembayaran',
                'url' => '/lap/pembayaran',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 8,
                'deleted_at' => '2025-04-23 09:06:07',
                'created_at' => '2025-02-25 13:24:53',
                'updated_at' => '2025-04-23 09:06:07',
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'Tagihanku',
                'url' => 'tagihanku',
                'route-name' => NULL,
                'icon' => 'fa fa-usd',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-04-23 09:03:04',
                'created_at' => '2025-03-08 15:15:50',
                'updated_at' => '2025-04-23 09:03:04',
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Tagihan Rutin',
                'url' => '/tagihanku/rutin',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 33,
                'deleted_at' => '2025-04-23 09:03:32',
                'created_at' => '2025-03-08 15:16:22',
                'updated_at' => '2025-04-23 09:03:32',
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'Tagihan Pam',
                'url' => '/tagihanku/pam',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 33,
                'deleted_at' => '2025-04-23 09:03:16',
                'created_at' => '2025-03-08 15:17:10',
                'updated_at' => '2025-04-23 09:03:16',
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Tagihan Ronda',
                'url' => '/tagihanku/ronda',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 33,
                'deleted_at' => '2025-04-23 09:02:46',
                'created_at' => '2025-03-08 15:17:53',
                'updated_at' => '2025-04-23 09:02:46',
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Tagihan Semua',
                'url' => '/tagihanku/semua',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 33,
                'deleted_at' => '2025-03-08 16:27:27',
                'created_at' => '2025-03-08 15:35:25',
                'updated_at' => '2025-03-08 16:27:27',
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'Keluargaku',
                'url' => '/keluarga',
                'route-name' => NULL,
                'icon' => 'fa fa-users',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-04-23 09:02:36',
                'created_at' => '2025-03-08 22:48:19',
                'updated_at' => '2025-04-23 09:02:36',
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'Simpan Surat',
                'url' => '/simpan',
                'route-name' => NULL,
                'icon' => 'fa fa-envelope',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-05-05 14:24:00',
                'created_at' => '2025-04-22 16:27:07',
                'updated_at' => '2025-05-05 14:24:00',
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'Surat Keluar',
                'url' => 'surat_keluar/',
                'route-name' => NULL,
                'icon' => 'fa fa-fast-forward',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-04-23 07:50:10',
                'created_at' => '2025-04-22 16:27:48',
                'updated_at' => '2025-04-23 07:50:10',
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'Surat Masuk',
                'url' => '/simpan/masuk',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 39,
                'deleted_at' => '2025-05-05 14:23:52',
                'created_at' => '2025-04-23 07:55:29',
                'updated_at' => '2025-05-05 14:23:52',
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'Surat Keluar',
                'url' => '/simpan/keluar',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 39,
                'deleted_at' => '2025-05-05 14:23:46',
                'created_at' => '2025-04-23 07:56:08',
                'updated_at' => '2025-05-05 14:23:46',
            ),
            42 => 
            array (
                'id' => 43,
                'title' => 'Berkas',
                'url' => '/simpan/berkas',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 39,
                'deleted_at' => '2025-05-05 14:23:40',
                'created_at' => '2025-04-23 07:56:40',
                'updated_at' => '2025-05-05 14:23:40',
            ),
            43 => 
            array (
                'id' => 44,
                'title' => 'Klasifikasi Surat',
                'url' => '/master/klasifikasi',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 7,
                'deleted_at' => '2025-05-05 14:23:33',
                'created_at' => '2025-04-23 07:59:32',
                'updated_at' => '2025-05-05 14:23:33',
            ),
            44 => 
            array (
                'id' => 45,
                'title' => 'Penandatangan',
                'url' => '/master/penandatangan',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 7,
                'deleted_at' => '2025-05-05 14:23:28',
                'created_at' => '2025-04-24 23:30:55',
                'updated_at' => '2025-05-05 14:23:28',
            ),
            45 => 
            array (
                'id' => 46,
                'title' => 'Buat Surat',
                'url' => '/buat',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-keyboard',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-05-05 14:23:22',
                'created_at' => '2025-04-28 22:00:02',
                'updated_at' => '2025-05-05 14:23:22',
            ),
            46 => 
            array (
                'id' => 47,
                'title' => 'Surat Dinas',
                'url' => '/buat/surat_dinas/create',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 46,
                'deleted_at' => '2025-05-05 14:23:11',
                'created_at' => '2025-04-28 22:06:55',
                'updated_at' => '2025-05-05 14:23:11',
            ),
            47 => 
            array (
                'id' => 48,
                'title' => 'Warga',
                'url' => '/master/warga',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 7,
                'deleted_at' => '2025-05-20 21:34:25',
                'created_at' => '2025-05-05 14:24:38',
                'updated_at' => '2025-05-20 21:34:25',
            ),
            48 => 
            array (
                'id' => 49,
                'title' => 'Sinkronisasi',
                'url' => '/sinkronisasi',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-database',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-06-09 11:38:02',
                'created_at' => '2025-05-23 10:30:43',
                'updated_at' => '2025-06-09 11:38:02',
            ),
            49 => 
            array (
                'id' => 50,
                'title' => 'Kegiatan',
                'url' => '/kegiatan',
                'route-name' => NULL,
                'icon' => 'fa fa-list-ol',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-06-09 11:37:57',
                'created_at' => '2025-05-28 14:31:14',
                'updated_at' => '2025-06-09 11:37:57',
            ),
            50 => 
            array (
                'id' => 51,
                'title' => 'Users',
                'url' => '/users',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 6,
                'deleted_at' => NULL,
                'created_at' => '2025-06-09 11:38:47',
                'updated_at' => '2025-06-09 11:38:47',
            ),
            51 => 
            array (
                'id' => 52,
                'title' => 'Log Activity',
                'url' => '/users/log',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 6,
                'deleted_at' => NULL,
                'created_at' => '2025-06-09 11:40:13',
                'updated_at' => '2025-06-18 09:52:06',
            ),
            52 => 
            array (
                'id' => 53,
                'title' => 'Periode Penilaian',
                'url' => '/periode',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-calendar-days',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-06-26 17:21:15',
                'created_at' => '2025-06-09 12:58:25',
                'updated_at' => '2025-06-26 17:21:15',
            ),
            53 => 
            array (
                'id' => 54,
                'title' => 'Jabatan',
                'url' => '/jabatan',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-stairs',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-06-26 17:21:20',
                'created_at' => '2025-06-09 13:00:10',
                'updated_at' => '2025-06-26 17:21:20',
            ),
            54 => 
            array (
                'id' => 55,
                'title' => 'Kriteria',
                'url' => '/kriteria',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-receipt',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-06-26 17:21:26',
                'created_at' => '2025-06-09 13:06:04',
                'updated_at' => '2025-06-26 17:21:26',
            ),
            55 => 
            array (
                'id' => 56,
                'title' => 'Penilaian',
                'url' => '/penilaian',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-pencil',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-06-26 17:21:31',
                'created_at' => '2025-06-09 13:07:17',
                'updated_at' => '2025-06-26 17:21:31',
            ),
            56 => 
            array (
                'id' => 57,
                'title' => 'Laporan',
                'url' => '/laporan',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-file-invoice',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-09 13:10:57',
                'updated_at' => '2025-06-25 19:18:37',
            ),
            57 => 
            array (
                'id' => 58,
                'title' => 'Karyawan',
                'url' => '/karyawan',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-clipboard-user',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-06-26 17:21:08',
                'created_at' => '2025-06-09 13:16:23',
                'updated_at' => '2025-06-26 17:21:08',
            ),
            58 => 
            array (
                'id' => 59,
                'title' => 'Management Stok',
                'url' => '/stok',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-cubes-stacked',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => '2025-06-30 22:06:49',
                'created_at' => '2025-06-18 10:28:25',
                'updated_at' => '2025-06-30 22:06:49',
            ),
            59 => 
            array (
                'id' => 60,
                'title' => 'Produk',
                'url' => '/pembelian/produk',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 76,
                'deleted_at' => NULL,
                'created_at' => '2025-06-18 10:30:08',
                'updated_at' => '2025-06-26 18:36:47',
            ),
            60 => 
            array (
                'id' => 61,
                'title' => 'Kategori Produk',
                'url' => '/stok/kategori',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 79,
                'deleted_at' => NULL,
                'created_at' => '2025-06-18 10:30:50',
                'updated_at' => '2025-06-29 17:45:37',
            ),
            61 => 
            array (
                'id' => 62,
                'title' => 'Kasir',
                'url' => '/kasir',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-cash-register',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 72,
                'deleted_at' => NULL,
                'created_at' => '2025-06-18 10:40:22',
                'updated_at' => '2025-06-25 20:30:21',
            ),
            62 => 
            array (
                'id' => 63,
                'title' => 'Bahan Baku',
                'url' => '/bahan',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-puzzle-piece',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 76,
                'deleted_at' => NULL,
                'created_at' => '2025-06-18 16:46:39',
                'updated_at' => '2025-06-26 17:18:44',
            ),
            63 => 
            array (
                'id' => 64,
                'title' => 'Penjualan',
                'url' => '/laporan/penjualan',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 57,
                'deleted_at' => NULL,
                'created_at' => '2025-06-25 19:17:57',
                'updated_at' => '2025-06-25 19:17:57',
            ),
            64 => 
            array (
                'id' => 67,
                'title' => 'Stok',
                'url' => '/laporan/stok',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => 57,
                'deleted_at' => NULL,
                'created_at' => '2025-06-25 19:27:00',
                'updated_at' => '2025-06-25 19:27:00',
            ),
            65 => 
            array (
                'id' => 68,
                'title' => 'Sisa Stok Bahan',
                'url' => '/laporan/stok_bahan',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 67,
                'deleted_at' => NULL,
                'created_at' => '2025-06-25 19:34:08',
                'updated_at' => '2025-06-30 22:06:01',
            ),
            66 => 
            array (
                'id' => 69,
                'title' => 'Sisa Stok Produk',
                'url' => '/laporan/stok_produk',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 67,
                'deleted_at' => NULL,
                'created_at' => '2025-06-25 19:34:41',
                'updated_at' => '2025-06-30 22:06:19',
            ),
            67 => 
            array (
                'id' => 70,
                'title' => 'Piutang Konsumen',
                'url' => '/laporan/piutang_konsumen',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 57,
                'deleted_at' => NULL,
                'created_at' => '2025-06-25 20:16:07',
                'updated_at' => '2025-06-25 20:16:07',
            ),
            68 => 
            array (
                'id' => 71,
                'title' => 'Pembelian',
                'url' => '/laporan/pembelian',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 57,
                'deleted_at' => NULL,
                'created_at' => '2025-06-25 20:23:12',
                'updated_at' => '2025-06-25 20:23:12',
            ),
            69 => 
            array (
                'id' => 72,
                'title' => 'Penjualan',
                'url' => '/penjualan',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-cart-plus',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-25 20:29:51',
                'updated_at' => '2025-06-25 20:30:01',
            ),
            70 => 
            array (
                'id' => 73,
                'title' => 'Piutang Konsumen',
                'url' => '/penjualan/piutang',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 72,
                'deleted_at' => NULL,
                'created_at' => '2025-06-25 20:31:58',
                'updated_at' => '2025-06-26 18:51:38',
            ),
            71 => 
            array (
                'id' => 74,
                'title' => 'Prediksi Kebutuhan Bahan',
                'url' => '/laporan/prediksi_bahan',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 67,
                'deleted_at' => NULL,
                'created_at' => '2025-06-25 22:20:30',
                'updated_at' => '2025-06-27 16:32:43',
            ),
            72 => 
            array (
                'id' => 75,
                'title' => 'Retur Penjualan',
                'url' => '/penjualan/retur',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 72,
                'deleted_at' => NULL,
                'created_at' => '2025-06-26 17:14:36',
                'updated_at' => '2025-06-26 17:14:36',
            ),
            73 => 
            array (
                'id' => 76,
                'title' => 'Pembelian',
                'url' => '/pembelian',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-cart-plus',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-26 17:15:59',
                'updated_at' => '2025-06-26 17:15:59',
            ),
            74 => 
            array (
                'id' => 77,
                'title' => 'Edit Transaksi',
                'url' => '/penjualan/edit',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 72,
                'deleted_at' => NULL,
                'created_at' => '2025-06-26 17:17:04',
                'updated_at' => '2025-07-02 21:14:07',
            ),
            75 => 
            array (
                'id' => 78,
                'title' => 'Asset',
                'url' => '/pembelian/asset',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 76,
                'deleted_at' => NULL,
                'created_at' => '2025-06-26 17:20:40',
                'updated_at' => '2025-06-26 17:20:40',
            ),
            76 => 
            array (
                'id' => 79,
                'title' => 'Master Data',
                'url' => '/master',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-database',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-26 17:23:04',
                'updated_at' => '2025-06-26 17:23:04',
            ),
            77 => 
            array (
                'id' => 80,
                'title' => 'Satuan',
                'url' => '/master/satuan',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 79,
                'deleted_at' => NULL,
                'created_at' => '2025-06-26 17:23:24',
                'updated_at' => '2025-06-26 17:23:24',
            ),
            78 => 
            array (
                'id' => 81,
                'title' => 'Supplier',
                'url' => '/master/supplier',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 79,
                'deleted_at' => NULL,
                'created_at' => '2025-06-26 17:24:41',
                'updated_at' => '2025-06-26 17:24:41',
            ),
            79 => 
            array (
                'id' => 82,
                'title' => 'Retur Pembelian',
                'url' => '/pembelian/retur',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 76,
                'deleted_at' => NULL,
                'created_at' => '2025-06-26 17:31:45',
                'updated_at' => '2025-06-29 18:26:25',
            ),
            80 => 
            array (
                'id' => 83,
                'title' => 'Jenis Pembayaran',
                'url' => '/master/jenis_pembayaran',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 79,
                'deleted_at' => NULL,
                'created_at' => '2025-06-26 17:34:22',
                'updated_at' => '2025-06-26 17:34:22',
            ),
            81 => 
            array (
                'id' => 84,
                'title' => 'Hutang',
                'url' => '/pembelian/hutang',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 76,
                'deleted_at' => NULL,
                'created_at' => '2025-06-28 19:43:08',
                'updated_at' => '2025-06-28 19:43:08',
            ),
            82 => 
            array (
                'id' => 85,
                'title' => 'Pengeluaran',
                'url' => '/pengeluaran',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-outdent',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-28 19:49:38',
                'updated_at' => '2025-06-28 19:57:47',
            ),
            83 => 
            array (
                'id' => 86,
                'title' => 'Operasional',
                'url' => '/pengeluaran/operasional',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 85,
                'deleted_at' => NULL,
                'created_at' => '2025-06-28 19:50:51',
                'updated_at' => '2025-06-28 19:50:51',
            ),
            84 => 
            array (
                'id' => 87,
                'title' => 'Laba Rugi',
                'url' => '/laporan/laba_rugi',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 57,
                'deleted_at' => NULL,
                'created_at' => '2025-06-28 19:51:57',
                'updated_at' => '2025-06-28 19:51:57',
            ),
            85 => 
            array (
                'id' => 88,
                'title' => 'Pengeluaran',
                'url' => '/laporan/pengeluaran',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 57,
                'deleted_at' => NULL,
                'created_at' => '2025-06-28 19:52:53',
                'updated_at' => '2025-06-28 19:52:53',
            ),
            86 => 
            array (
                'id' => 89,
                'title' => 'Keuangan',
                'url' => '/keuangan',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-money-bill-1-wave',
                'caret' => 1,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-28 19:55:32',
                'updated_at' => '2025-06-28 19:57:29',
            ),
            87 => 
            array (
                'id' => 90,
                'title' => 'Kas Masuk / Keluar',
                'url' => '/keuangan/kas',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 89,
                'deleted_at' => NULL,
                'created_at' => '2025-06-28 19:58:55',
                'updated_at' => '2025-06-28 19:58:55',
            ),
            88 => 
            array (
                'id' => 91,
                'title' => 'Rekening Bank',
                'url' => '/keuangan/rekening',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 89,
                'deleted_at' => NULL,
                'created_at' => '2025-06-28 19:59:17',
                'updated_at' => '2025-06-28 19:59:17',
            ),
            89 => 
            array (
                'id' => 92,
                'title' => 'Pemasukan',
                'url' => '/pemasukan/pemasukan',
                'route-name' => NULL,
                'icon' => 'fa-solid fa-indent',
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 11:24:22',
                'updated_at' => '2025-06-29 16:00:04',
            ),
            90 => 
            array (
                'id' => 93,
                'title' => 'Pengeluaran Lain',
                'url' => '/pengeluaran/lain',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 85,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 11:27:40',
                'updated_at' => '2025-06-29 11:27:40',
            ),
            91 => 
            array (
                'id' => 94,
                'title' => 'Komponen Produksi',
                'url' => '/master/komponen',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => 79,
                'deleted_at' => NULL,
                'created_at' => '2025-07-01 01:34:22',
                'updated_at' => '2025-07-01 01:35:07',
            ),
            92 => 
            array (
                'id' => 95,
                'title' => 'forcastingM2block',
                'url' => '/mblock',
                'route-name' => NULL,
                'icon' => NULL,
                'caret' => 0,
                'aktif' => 1,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-02 22:10:06',
                'updated_at' => '2025-07-02 22:10:06',
            ),
        ));
        
        
    }
}